---
title: "SeaFET and EcoPar Report"
author: "Patrick Kiel"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)

library(tidyverse)
library(lubridate)

```

```{r load data}
  PAR <- read_csv('./DRTO_EcoPAR07062021.csv') %>%
          mutate(DateTime = mdy_hms(paste(Date, Time))) %>%
          select(DateTime, `PAR (CALC)`) %>%
          drop_na() %>%
          mutate(interval = 0:(nrow(.)-1) %/% 10) %>%
          group_by(interval) %>%
          summarise(DateTime = mean(DateTime),
                    PAR = mean(`PAR (CALC)`),
                    sd = sd(`PAR (CALC)`)) %>%
        select(-interval) %>%
  #manual start/stop time of monitoring
  filter(DateTime >= as.POSIXct('2021-06-25 18:35:00', tz='UTC') &
         DateTime <= as.POSIXct('2021-06-28 19:45:00', tz='UTC')) %>%
  mutate(DateTime = with_tz(DateTime, 'America/New_York'))
  
  pH <- read_csv('./DRTO_SeaFET07062021.csv') %>%
    select(DateTime = `DateTime (UTC+00:00)`,
           pH = `Internal pH (pH)`,
           Temperature = `pH Temperature (Celsius)`) %>%
    mutate(DateTime = parse_date_time(DateTime, '%m/%d/%Y %H:%M')) %>%
    #manual start/stop time of monitoring
   filter(DateTime >= as.POSIXct('2021-06-25 18:35:00', tz='UTC') &
         DateTime <= as.POSIXct('2021-06-28 19:45:00', tz='UTC')) %>%
  mutate(DateTime = with_tz(DateTime, 'America/New_York'))
```

```{r create graphs}
PAR %>%
  ggplot(aes(x=DateTime, y=PAR)) +
  geom_line(color = "blue", size=1) + 
  theme_bw() +
  labs(title = "PAR of NCRMP-DRTO Plots Jun 26 - 28 '21",
       y = expression(paste("PAR (",mu,"mol photons m"^-2,"s"^-1,")")),
       x = "Time of Day (EDT)") +
  scale_x_datetime(date_breaks = "6 hour",
                   date_minor_breaks = "3 hour",
                   date_labels = "%H:%M")



pH %>%
  ggplot(aes(x=DateTime, y=pH)) +
  geom_line(color = "red", size=1) + 
  theme_bw() +
  labs(title = "pH of NCRMP-DRTO Plots Jun 26 - 28 '21",
       y = "pH",
       x = "Time of Day (EDT)") +
  scale_x_datetime(date_breaks = "6 hour",
                   date_minor_breaks = "3 hour",
                   date_labels = "%H:%M")

#pH and light combined-----
PAR.adj <- PAR %>%
  mutate(PAR = PAR*0.0001 + 7.93)

ggplot() +
  geom_line(data = pH, aes(x=DateTime, y=pH),
            color = "red", size=1) +
    geom_line(data = PAR.adj, aes(x=DateTime, y=PAR),
            color = "blue", size=1, alpha = 0.5) +
  labs(title = "NCRMP-DRTO Data Jun 26 - 28 '21",
       y = "pH",
       x = "Time of Day (EDT)") +
  scale_y_continuous(limits = c(7.93,7.98), sec.axis = sec_axis(~(.-7.93)/0.0001)) +
  scale_x_datetime(date_breaks = "6 hour",
                   date_minor_breaks = "3 hour",
                   date_labels = "%H:%M") +
  annotate("text",
           label = expression(paste("PAR (",mu,"mol photons m"^-2,"s"^-1,")")),
           angle=90,
           x = max(pH$DateTime+(3600*12)),
           y = 7.95) + 
  coord_cartesian(ylim = c(7.925,7.985),
                    xlim = c(min(pH$DateTime),max(pH$DateTime)),
                    expand = T,
                    clip = 'off') +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.margin = unit(c(1,3,1,1), "lines"))


#pH and temp combined -----
pH$Temp.adj <- (pH$Temperature * 0.1099) + 4.8371

ggplot(data = pH) +
  annotate("rect",
          xmin = seq.POSIXt(as.POSIXct('2021-06-25 19:00:00', tz='EST'),
                         by = "day", length.out = 3),
          xmax = seq.POSIXt(as.POSIXct('2021-06-26 08:00:00', tz='EST'),
                         by = "day", length.out = 3),
          ymin = -Inf, ymax = Inf,
          fill="grey", alpha=0.5) +
  geom_line(aes(x=DateTime, y=pH, color = "pH"),
            size=1) +
  geom_line(aes(x=DateTime, y=Temp.adj, color = "Temperature"),
            size=0.7, alpha = 0.5) +
  labs(title = "NCRMP-DRTO Data Jun 25 - 28 '21",
       y = "pH",
       x = "Time of Day (EDT)") +
  scale_y_continuous(limits = c(7.925,7.985), sec.axis = sec_axis(~(.-4.8371)/0.1099)) +
  scale_x_datetime(date_breaks = "6 hour",
                   date_minor_breaks = "3 hour",
                   date_labels = "%H:%M") +
  annotate("text",
           label = expression(paste("Temperature (",degree,"C)")),
           angle=90,
           x = max(pH$DateTime+(3600*10)),
           y = 7.95) + 
  coord_cartesian(ylim = c(7.925,7.985),
                    xlim = c(min(pH$DateTime),max(pH$DateTime)),
                    clip = 'off',
                    expand = T) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.margin = unit(c(1,3,1,1), "lines"),
        legend.position = "bottom") +
  annotate("text",
          label = paste("Jun", 25:28),
          x = seq.POSIXt(as.POSIXct('2021-06-25 13:30:00', tz='EST'),
                         by = "day", length.out = 4),
          y = 7.985)
```
